package com.example.CloudBalanceBackend.dto;

public enum ECostExplorerServices {

    MYCLOUD_INSTANCETYPE,
    LINKEDACCOUNTID,
    LINEITEM_USAGETYPE,

    MYCLOUD_REGIONNAME,
    MYCLOUD_COST_EXPLORER_USAGE_GROUP_TYPE,
    MYCLOUD_PRICINGTYPE,
    LINEITEM_OPERATION,

    CHARGE_TYPE,
    AVAILABILITYZONE,
    TENANCY,

//    MYCLOUD_OPERATINGSYSTEM,
//    MYCLOUD_STARTDAY,
//    USAGESTARTDATE,
//    LINEITEM_UNBLENDEDCOST,
//    MYCLOUD_STARTMONTH,
//    PRICING_UNIT,
//    PRODUCT_DATABASEENGINE,
//    LINEITEM_USAGEAMOUNT,
//    MYCLOUD_STARTYEAR,
//    PRODUCT_PRODUCTNAME
}
