spring:
  application:
    name: CloudBalanceBackend

# Database Connection
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/cloudBalance
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Properties
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    # hibernate.ddl-auto: create-drop
    show-sql: true

  snowflake:
    url: jdbc:snowflake://YFYRZGG-BWB35436.snowflakecomputing.com/?db=aws&schema=cost&warehouse=SYSTEM$STREAMLIT_NOTEBOOK_WH
    username: ro_user
    password: fRe$her@b00tc@mp2025
#    warehouse: COMPUTE_WH
    driver-class-name: net.snowflake.client.jdbc.SnowflakeDriver


jwtUtil:
  app:
    jwtSecret: "S3cuR3JWTsTr1Ng1234567890SuperLongKey"
    jwtAccessExpirationMs: 900000
    jwtRefreshExpirationMs: 604800000

aws:
  region: as-east-1
  access-key: YOUR_ACCESS_KEY
  secret-key: YOUR_SECRET_KEY


